apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-cnd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-cnd
    spec:
      containers:
      - image: pchico83/go-cnd:0.2
        name: go-cnd
        ports:
        - containerPort: 8080
