apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-cnd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-cnd
    spec:
      containers:
      - image: pchico83/python-cnd:0.1
        name: vote