apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cnd
  labels:
    app: python-cnd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-cnd
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - image: pchico83/python-cnd:0.1
        name: vote